[theme]
primaryColor = "#1F51FF"              # Bright yellow for contrast and highlights
backgroundColor = "#1e1e1e"           # Deep gray background
secondaryBackgroundColor = "#2e2e2e"  # Slightly lighter gray for containers/cards
textColor = "#f5f5f5"                 # Soft white text for readability
font = "sans serif"                   # Clean and modern font